---
- name: disable backend
  haproxy:
    state: drain
    host: '{{ inventory_hostname }}'
    socket: /var/run/haproxy.sock
    backend: api
    wait: yes
  delegate_to: "{{ item }}"
  with_items: "{{ groups['lb'] }}"
